### ISSUE TITLE
Weekly Scrum - Mar 8, 2023

### ISSUE THREAD

**Issue by robellgabriel** [CarletonU-2223-SAV/SYSC4806-Project#23]

**Comment by nicolastuttle** [comment]
### What have I done this week?

Configured CI (#1), created the home page (#5), implemented RestController for book (#10), handle image uploads (#20)

### What will I do next week?

Configure a separate DB for tests (#27), deploy the app to AWS Lambda (#26) -- can it be done with CI? Need to investigate.

### What is holding me back?

Nada

**Comment by phucla0122** [comment]
What have I done this week?

- Create add, edit, and delete book feature
- Create test cases for the mentioned feature 

What will I do next week?

- Create the recommendation feature (https://github.com/CarletonU-2223-SAV/SYSC4806-Project/issues/25)
- Create the active user feature for the bookstore, separate the customer and admin (https://github.com/CarletonU-2223-SAV/SYSC4806-Project/issues/28)

What is holding me back?

N/A

**Comment by robellgabriel** [comment]
###  What have I done this week?

- implement restController for shoppingcart and users (#16)
- created shopping cart page with feautures in cart controller (#21)

### What will I do next week?

- Refactor current design so Users holds Shopping Carts (#29)
- Create checkout page (#24)

What is holding me back?

N/A
