### ISSUE TITLE
Weekly Scrum - Feb 27, 2023

### ISSUE THREAD

**Issue by robellgabriel** [CarletonU-2223-SAV/SYSC4806-Project#3]

**Comment by nicolastuttle** [comment]
### What have I done this week?

Nothing yet! This is the first week.

### What will I do next week?

Add CI to the project (#1), create a RestController for Book (#10), create the bookstore's homepage (#5)

### What is holding me back?

Nada

**Comment by robellgabriel** [comment]
### What have I done this week? 
N/A

### What will I do next week?  
create RestControllers for shopping cart and user models (#10), and create a page managing the shopping cart (#6)

### What is holding me back? 
N/A

**Comment by phucla0122** [comment]
**What have I done this week?**

N/A

**What will I do next week?**

create a page to add a new book or edit a book (#4), and develop the project model for user, shopping cart and book (#2)

**What is holding me back?**

N/A
