### ISSUE TITLE
Weekly Scrum - Mar 15, 2023

### ISSUE THREAD

**Issue by nicolastuttle** [CarletonU-2223-SAV/SYSC4806-Project#32]

**Comment by nicolastuttle** [comment]
### What have I done this week?

Configured a separate DB for tests (#27)

### What will I do next week?

Deploy the app to Azure Functions (#26) -- can it be done with CI? Need to investigate.

### What is holding me back?

Having to prioritize other projects

**Comment by robellgabriel** [comment]
### What have I done this week?

Refactored User Model to hold Shopping Cart (#31)

### What will I do next week?

Implement a checkout page with controllers (#24)

### What is holding me back?

Finding time to work, other project deadlines due this week

**Comment by phucla0122** [comment]
What have I done this week?
Working on creating active users (https://github.com/CarletonU-2223-SAV/SYSC4806-Project/issues/28)

What will I do next week?
Finish working on creating active users (https://github.com/CarletonU-2223-SAV/SYSC4806-Project/issues/28)
Implement the recommendation feature (https://github.com/CarletonU-2223-SAV/SYSC4806-Project/issues/25)

What is holding me back?
Have to prioritize other courses' project
