### ISSUE TITLE
Weekly Scrum - Mar 22, 2023

### ISSUE THREAD

**Issue by nicolastuttle** [CarletonU-2223-SAV/SYSC4806-Project#44]

**Comment by nicolastuttle** [comment]
### What have I done this week?

Developed an Azure Function to serve shipping costs to the checkout page (#26)

### What will I do next week?

Split Book-related tests into their own classes (#51) and simplify shipping costs Azure Function (#50)

### What is holding me back?

Learning how to use Azure from scratch

**Comment by phucla0122** [comment]
**What have I done this week?**
- Create active user, which is the login, logout, and sign up for the user (#28)
- Create a recommendation feature for the bookstore (#25)

**What will I do next week?**
- Improve the recommendation feature (#46)
- Refactor the shopping cart and image integration tests (#49)

**What is holding me back?**
N/A

**Comment by robellgabriel** [comment]
### What have I done this week?
Implemented a checkout page with a price tag and total costs (#42) 

### What will I do next week?
Split User-related tests into their respectice test classes (#52) and include an order history page (#45)

### What is holding me back?
N/A
