### ISSUE TITLE
Weekly Scrum - Apr 5, 2023

### ISSUE THREAD

**Issue by nicolastuttle** [CarletonU-2223-SAV/SYSC4806-Project#63]

**Comment by nicolastuttle** [comment]
### What have I done this week?

Split Book/BookstoreController/BookService tests into their own classes (#53), refactor Azure function call to only take an int (#54), added shipping timeline and order confirmation page (#60)

### What will I do next week?

Study for exams

### What is holding me back?

Nada

**Comment by robellgabriel** [comment]
### What have I done this week?

Splitted the User Model, Controller, and Service tests into their own respective classes (#59) and added an order history page showing all of user's past book orders (#61)

### What will I do next week?

Finish up semester workload and study for exams

### What is holding me back?

N/A

**Comment by phucla0122** [comment]
**What have I done this week?**

Created the integration test for the image controller (#56)
Separate the integration tests for the shopping cart controller (#49)
Improve the book recommendation with Jaccard Distance algorithm (#46)

**What will I do next week?**
Study for final exams

**What is holding me back?**
N/A
